### ISSUE TITLE
Cloudflare now provides an official arm64 Docker image for cloudflared

### ISSUE THREAD

**Issue by marazmarci** [milgradesec/cloudflared-docker#37]
Hi, I just wanted to let you know that Cloudflare now provides an official `linux/arm64` Docker image for `cloudflared`.

You can confirm it by running this command on a Raspberry Pi with a 64-bit OS:
```
docker run cloudflare/cloudflared tunnel --hello-world
```

They added support very recently (on 12th August) with this file:
https://github.com/cloudflare/cloudflared/blob/master/Dockerfile.arm64

By the way, thanks very much for your Docker image. I was using it until this very point. ❤️

**Comment by milgradesec** [comment]
Thank you, I will keep maintaining this image for some time. Older Raspberry Pi's with `armhf` architecture dont work with `linux/arm64` images and they need `linux/armv7`
